### ISSUE TITLE
Making microconsulting pay

### ISSUE THREAD

**Issue by mdoneill** [department-of-veterans-affairs/VA-Micropurchase-Repo#9]
Since this feedback applies to microconsulting in general and not specifically to any one of the draft work statements, I started a new issue... 

Microconsulting is a powerful way to engage specific resources to deliver specific results in areas that directly match needs with core competence. Based on the experience that I've had, and that my company (MedicaSoft) has had, with VA's innovation program and the OSEHRA open source community, there are two important areas to focus on in order to reap the benefits: pre-task preparation and post-task integration.

By definition, microconsulting breaks work down into small tasks that can be rapidly executed by a few well-matched resources. In order for those resources to be effective in executing the task quickly, everything must be lined up in advance. For a development task, for example, questions of system architecture, data sources, target systems, security, test approach, etc. must be well understood and communicated in advance, and the logistics of system access, access to specifications, schemas, permissions, etc. must be in place. If this preparatory work is not firmly in place, the odds are that the micro-task will deliver not degraded outcomes, but no usable outcome at all.

Also by definition, the output of each microconsulting task is a small part of a larger system. The micro-task is focused on accomplishing a specific goal and not on integration with the larger system. Post-task integration is required to take individual micro-deliverables and make them a usable part of the larger system. This is true for software deliverables and for non-software deliverables; an analysis deliverable may need to become part of a system design, for example. Great pre-task preparation can make post-task integration easier, but experience shows that post-task integration requires substantially more effort than the task itself, and if it isn't done soon after the micro-task completes, there is a high probability that the micro-deliverable is orphaned and the benefit is lost altogether. 

It's not a groundbreaking insight to say that you have to prepare before executing a task and you have to do work to make the results useful. Experience shows, however, that it is not easy to keep up the sustained focus on pre- and post-task efforts that is required to make a long-term microconsulting approach successful. There are plenty of examples (in government and the private sector) of contests, competitions, and innovation programs that launched well and faltered because they didn't have this level of sustained focus.

**Comment by pbradley25** [comment]
I think it’s helpful to talk about what success looks like. When this Next Generation Open Digital Platform is successful, what does this success look like to developers, business and product owners, Veterans and other stakeholders? What are some of the obstacles to success?  Here are a few thoughts…

Lighthouse will be a success if a large number of VA “business owners”, “product owners” and innovators have the ability to make or buy applications leveraging a rich set of VA (and non-VA) data and services enabled through Lighthouse – and do so much more quickly than they can today, with lower costs and higher-quality solutions.  To the extent that the collection of business owners and product owners are also the VA “data owners” this can work – as getting access to the data is one of the biggest challenges at VA. 

To me, success is a platform that enables the design, development and deployment of a moderately complex applications in 6 months or less. This should be the norm not the exception. Today we have 4-6 month acquisition cycles followed by 12 – 18 month design, development and deployment cycles.  VIP has helped but much more can be done to make the 6-month goal a reality – and Lighthouse can be a driver for this.

A first step is demonstrating that a handful of microconsulting contracts for moderately complex solutions, not just APIs, can be competed and awarded in 1-2 months. If the work can be done without requiring access to the VA network, great, but that’s not the norm. So the next big challenge is figuring out how to get microconsultants VA access within 1-2 weeks.  Or....  Is it possible to award the microconsulting contracts under a Multiple Award Indefinite Delivery Indefinite Quantity (MAIDIQ) so that each quarter a pool of qualified developers can be onboarded in advance of each microconsulting award? Perhaps this is not feasible but the thought of not having to wait 6-8 weeks for a PIV makes me smile.

Another big challenge is security. Clearly the security of VA’s systems and data cannot be compromised in this initiative. Establishing and maintaining security is hard, and expensive. Currently, navigating the compliance process, obtaining an Authority to Operate, and getting listed on the Technical Reference Model is a long process. Even if you can develop an application in 4-6 months it can take another 6-12 months (or more) to obtain all the necessary approvals to deploy a solution into production. I hope and expect that Lighthouse will improve security, reduce complexity and ease the compliance burden placed on developers by establishing a platform, including microservices and API architectures with the necessary standards and controls in place. Yes?  Is it reasonable to assume the compliance process can be reduced from 6-12 months to 1-2 months for a moderately complex application/system?  If Lighthouse promotes a highly-automated governance process, I can start to envision an innovative development and delivery environment where we can move from idea to production in 6 months.

One other tangent.   Imagine a development project that needs to satisfy 60 user stories. Instead of awarding this work to one organization with one scrum team of 6-8 developers with a period of performance of 10 two-week sprints, the work is awarded as microconsulting contracts. Let’s think about creating an environment where 6-8 independent microconsultants work together more efficiently and effectively than the one organization? Here we need to consider the tremendous value of creativity, diversity of thought, and competition that can be realized with microconsulting. What about 60 independent microconsultants each owning a user story and each completing their work in a single two-week sprint?  Are there any examples of this in the commercial or federal space?
